url_articulos = "Sistema_Compras_TK/Archivos guardados/datos_tabla_Articulos.pkl"
url_clientes = "Sistema_Compras_TK/Archivos guardados/datos_tabla_Clientes.pkl"
url_empleados = "Sistema_Compras_TK/Archivos guardados/datos_tabla_Empleados.pkl"
url_proveedores = "Sistema_Compras_TK/Archivos guardados/datos_tabla_Proveedores.pkl"
url_noFactura = "Sistema_Compras_TK/Archivos guardados/numeros_factura.pkl"
